- name: Setup webservers
  hosts: webservers
  become: true

  vars:
    pip_install_packages:
      - name: docker

  pre_tasks:
    - ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 604800

  roles:
    - geerlingguy.pip
